name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        # ftp-server: ${{ secrets.ESIAM_FTP_SERVER }}
        ftp-server: sftp://sftp.student.politeknikmeta.ac.id
        ftp-username: ${{ secrets.ESIAM_FTP_USERNAME }}
        ftp-password: ${{ secrets.ESIAM_FTP_PASSWORD }}
