@extends('layouts.master')

@section('side')

  @include('layouts.side')

@endsection
@section('content')
  <section class="content">
    <div class="row">
      <div class="col-md-6">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Record Pembayaran</h3>
          </div>
          <div class="box-body">
            <table  class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>Item Bayar</th>
                <th>Tanggal Bayar</th>
                <th>Nomor Kuitansi</th>
                <th>Nominal Bayar</th>
              </tr>
              </thead>
              <tbody>
              @foreach ($kuit as $key)
                <tr>
                  <td>
                    @foreach ($itembayar as $item)
                      @if ($key->iditem == $item->iditem)
                        {{$item->item}}
                      @endif
                    @endforeach
                    </td>
                  <td align="center">{{$key->tanggal}}</td>
                  <td align="center">{{$key->nokuit}}</td>
                  <td align="right">@currency($key->bayar)</td>
                </tr>
              @endforeach
              <tr>
                <td align="center" colspan="3"><b>Total Bayar</b></td>
                <td align="right"><b>@currency($totalbayarmhs)</b></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Tabel Biaya Selama Kuliah</h3>
          </div>
          <div class="box-body">
            <table class="table table-bordered">
              <tr>
                <th><center>Item</center></th>
                <th width="4px"><center>Beasiswa</center></th>
                <th><center>Total Bayar</center></th>
                <th><center>Telah dibayar</center></th>
                <th><center>Sisa Bayar</center></th>
              </tr>
              <tr>
                @foreach ($items as $ikey)
                  <tr>
                    <td>{{$ikey->item}}</td>
                    <td><center>
                      @if ($ikey->item=='Pendaftaran')
                              {{$beadaftar}}%
                            @elseif ($ikey->item=='Perlengkapan Awal')
                              {{$beaawal}}%
                            @elseif ($ikey->item=='Dana Pengembangan')
                              {{$beadsp}}%
                            @elseif ($ikey->item=='Biaya SPP 1')
                              {{$beaspp1}}%
                            @elseif ($ikey->item=='Biaya SPP 2')
                              {{$beaspp2}}%
                            @elseif ($ikey->item=='Biaya SPP 3')
                              {{$beaspp3}}%
                            @elseif ($ikey->item=='Biaya SPP 4')
                              {{$beaspp4}}%
                            @elseif ($ikey->item=='Biaya SPP 5')
                              {{$beaspp5}}%
                            @elseif ($ikey->item=='Biaya SPP 6')
                              {{$beaspp6}}%
                            @elseif ($ikey->item=='Biaya SPP 7')
                              {{$beaspp7}}%
                            @elseif ($ikey->item=='Biaya SPP 8')
                              {{$beaspp8}}%
                            @elseif ($ikey->item=='Biaya SPP 9')
                              {{$beaspp9}}%
                            @elseif ($ikey->item=='Biaya SPP 10')
                              {{$beaspp10}}%
                            @elseif ($ikey->item=='Seminar')
                              {{$beasmn}}%
                            @elseif ($ikey->item=='Sidang')
                              {{$beasdg}}%
                            @elseif ($ikey->item=='Wisuda')
                              {{$beawsd}}%
                          @endif
                    </center></td>
                    <td align="right">@if ($ikey->item=='Pendaftaran')
                          @if ($c==4)
                              @currency($daftar*$ikey->year22)
                            @elseif ($c==2)
                              @currency($daftar*$ikey->year12)
                            @elseif ($c==3)
                              @currency($daftar*$ikey->year21)
                            @elseif ($c==1)
                              @currency($daftar*$ikey->year11)
                            @elseif ($c==5)
                              @currency($daftar*$ikey->year31)
                            @elseif ($c==6)
                              @currency($daftar*$ikey->year32)
                            @elseif ($c==7)
                              @currency($daftar*$ikey->year41)
                            @elseif ($c==8)
                              @currency($daftar*$ikey->year42)
                            @elseif ($c==9)
                              @currency($daftar*$ikey->year51)
                            @elseif ($c==10)
                              @currency($daftar*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Perlengkapan Awal')
                          @if ($c==4)
                              @currency($awal*$ikey->year22)
                            @elseif ($c==2)
                              @currency($awal*$ikey->year12)
                            @elseif ($c==3)
                              @currency($awal*$ikey->year21)
                            @elseif ($c==1)
                              @currency($awal*$ikey->year11)
                            @elseif ($c==5)
                              @currency($awal*$ikey->year31)
                            @elseif ($c==6)
                              @currency($awal*$ikey->year32)
                            @elseif ($c==7)
                              @currency($awal*$ikey->year41)
                            @elseif ($c==8)
                              @currency($awal*$ikey->year42)
                            @elseif ($c==9)
                              @currency($awal*$ikey->year51)
                            @elseif ($c==10)
                              @currency($awal*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Dana Pengembangan')
                          @if ($c==4)
                              @currency($dsp*$ikey->year22)
                            @elseif ($c==2)
                              @currency($dsp*$ikey->year12)
                            @elseif ($c==3)
                              @currency($dsp*$ikey->year21)
                            @elseif ($c==1)
                              @currency($dsp*$ikey->year11)
                            @elseif ($c==5)
                              @currency($dsp*$ikey->year31)
                            @elseif ($c==6)
                              @currency($dsp*$ikey->year32)
                            @elseif ($c==7)
                              @currency($dsp*$ikey->year41)
                            @elseif ($c==8)
                              @currency($dsp*$ikey->year42)
                            @elseif ($c==9)
                              @currency($dsp*$ikey->year51)
                            @elseif ($c==10)
                              @currency($dsp*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 1')
                          @if ($c==4)
                              @currency($spp1*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp1*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp1*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp1*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp1*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp1*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp1*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp1*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp1*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp1*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 2')
                          @if ($c==4)
                              @currency($spp2*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp2*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp2*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp2*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp2*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp2*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp2*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp2*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp2*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp2*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 3')
                          @if ($c==4)
                              @currency($spp3*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp3*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp3*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp3*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp3*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp3*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp3*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp3*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp3*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp3*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 4')
                          @if ($c==4)
                              @currency($spp4*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp4*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp4*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp4*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp4*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp4*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp4*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp4*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp4*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp4*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 5')
                          @if ($c==4)
                              @currency($spp5*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp5*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp5*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp5*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp5*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp5*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp5*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp5*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp5*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp5*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 6')
                          @if ($c==4)
                              @currency($spp6*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp6*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp6*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp6*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp6*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp6*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp6*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp6*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp6*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp6*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 7')
                          @if ($c==4)
                              @currency($spp7*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp7*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp7*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp7*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp7*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp7*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp7*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp7*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp7*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp7*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 8')
                          @if ($c==4)
                              @currency($spp8*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp8*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp8*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp8*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp8*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp8*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp8*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp8*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp8*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp8*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 9')
                          @if ($c==4)
                              @currency($spp9*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp9*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp9*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp9*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp9*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp9*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp9*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp9*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp9*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp9*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Biaya SPP 10')
                          @if ($c==4)
                              @currency($spp10*$ikey->year22)
                            @elseif ($c==2)
                              @currency($spp10*$ikey->year12)
                            @elseif ($c==3)
                              @currency($spp10*$ikey->year21)
                            @elseif ($c==1)
                              @currency($spp10*$ikey->year11)
                            @elseif ($c==5)
                              @currency($spp10*$ikey->year31)
                            @elseif ($c==6)
                              @currency($spp10*$ikey->year32)
                            @elseif ($c==7)
                              @currency($spp10*$ikey->year41)
                            @elseif ($c==8)
                              @currency($spp10*$ikey->year42)
                            @elseif ($c==9)
                              @currency($spp10*$ikey->year51)
                            @elseif ($c==10)
                              @currency($spp10*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Seminar')
                          @if ($c==4)
                              @currency($seminar*$ikey->year22)
                            @elseif ($c==2)
                              @currency($seminar*$ikey->year12)
                            @elseif ($c==3)
                              @currency($seminar*$ikey->year21)
                            @elseif ($c==1)
                              @currency($seminar*$ikey->year11)
                            @elseif ($c==5)
                              @currency($seminar*$ikey->year31)
                            @elseif ($c==6)
                              @currency($seminar*$ikey->year32)
                            @elseif ($c==7)
                              @currency($seminar*$ikey->year41)
                            @elseif ($c==8)
                              @currency($seminar*$ikey->year42)
                            @elseif ($c==9)
                              @currency($seminar*$ikey->year51)
                            @elseif ($c==10)
                              @currency($seminar*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Sidang')
                          @if ($c==4)
                              @currency($sidang*$ikey->year22)
                            @elseif ($c==2)
                              @currency($sidang*$ikey->year12)
                            @elseif ($c==3)
                              @currency($sidang*$ikey->year21)
                            @elseif ($c==1)
                              @currency($sidang*$ikey->year11)
                            @elseif ($c==5)
                              @currency($sidang*$ikey->year31)
                            @elseif ($c==6)
                              @currency($sidang*$ikey->year32)
                            @elseif ($c==7)
                              @currency($sidang*$ikey->year41)
                            @elseif ($c==8)
                              @currency($sidang*$ikey->year42)
                            @elseif ($c==9)
                              @currency($sidang*$ikey->year51)
                            @elseif ($c==10)
                              @currency($sidang*$ikey->year52)
                          @endif
                        @elseif ($ikey->item=='Wisuda')
                          @if ($c==4)
                              @currency($wisuda*$ikey->year22)
                            @elseif ($c==2)
                              @currency($wisuda*$ikey->year12)
                            @elseif ($c==3)
                              @currency($wisuda*$ikey->year21)
                            @elseif ($c==1)
                              @currency($wisuda*$ikey->year11)
                            @elseif ($c==5)
                              @currency($wisuda*$ikey->year31)
                            @elseif ($c==6)
                              @currency($wisuda*$ikey->year32)
                            @elseif ($c==7)
                              @currency($wisuda*$ikey->year41)
                            @elseif ($c==8)
                              @currency($wisuda*$ikey->year42)
                            @elseif ($c==9)
                              @currency($wisuda*$ikey->year51)
                            @elseif ($c==10)
                              @currency($wisuda*$ikey->year52)
                          @endif
                    @endif</td>
                    <td align="right">@if ($ikey->item=='Pendaftaran')
                            @currency($sisadaftar)
                          @elseif ($ikey->item=='Perlengkapan Awal')
                            @currency($sisaawal)
                          @elseif ($ikey->item=='Dana Pengembangan')
                            @currency($sisadsp)
                          @elseif ($ikey->item=='Biaya SPP 1')
                            @currency($sisaspp1)
                          @elseif ($ikey->item=='Biaya SPP 2')
                            @currency($sisaspp2)
                          @elseif ($ikey->item=='Biaya SPP 3')
                            @currency($sisaspp3)
                          @elseif ($ikey->item=='Biaya SPP 4')
                            @currency($sisaspp4)
                          @elseif ($ikey->item=='Biaya SPP 5')
                            @currency($sisaspp5)
                          @elseif ($ikey->item=='Biaya SPP 6')
                            @currency($sisaspp6)
                          @elseif ($ikey->item=='Biaya SPP 7')
                            @currency($sisaspp7)
                          @elseif ($ikey->item=='Biaya SPP 8')
                            @currency($sisaspp8)
                          @elseif ($ikey->item=='Biaya SPP 9')
                            @currency($sisaspp9)
                          @elseif ($ikey->item=='Biaya SPP 10')
                            @currency($sisaspp10)
                          @elseif ($ikey->item=='Seminar')
                            @currency($sisaseminar)
                          @elseif ($ikey->item=='Sidang')
                            @currency($sisasidang)
                          @elseif ($ikey->item=='Wisuda')
                            @currency($sisawisuda)
                        @endif
                      </td>
                      <td align="right">
                        @if ($ikey->item=='Pendaftaran')
                              @if ($c==4)
                                  @currency(($daftar*$ikey->year22)-$sisadaftar)
                                @elseif ($c==2)
                                  @currency(($daftar*$ikey->year12)-$sisadaftar)
                                @elseif ($c==3)
                                  @currency(($daftar*$ikey->year21)-$sisadaftar)
                                @elseif ($c==1)
                                  @currency(($daftar*$ikey->year11)-$sisadaftar)
                                @elseif ($c==5)
                                  @currency(($daftar*$ikey->year31)-$sisadaftar)
                                @elseif ($c==6)
                                  @currency(($daftar*$ikey->year32)-$sisadaftar)
                                @elseif ($c==7)
                                  @currency(($daftar*$ikey->year41)-$sisadaftar)
                                @elseif ($c==8)
                                  @currency(($daftar*$ikey->year42)-$sisadaftar)
                                @elseif ($c==9)
                                  @currency(($daftar*$ikey->year51)-$sisadaftar)
                                @elseif ($c==10)
                                  @currency(($daftar*$ikey->year52)-$sisadaftar)
                              @endif
                            @elseif ($ikey->item=='Perlengkapan Awal')
                              @if ($c==4)
                                  @currency(($awal*$ikey->year22)-$sisaawal)
                                @elseif ($c==2)
                                  @currency(($awal*$ikey->year12)-$sisaawal)
                                @elseif ($c==3)
                                  @currency(($awal*$ikey->year21)-$sisaawal)
                                @elseif ($c==1)
                                  @currency(($awal*$ikey->year11)-$sisaawal)
                                @elseif ($c==5)
                                  @currency(($awal*$ikey->year31)-$sisaawal)
                                @elseif ($c==6)
                                  @currency(($awal*$ikey->year32)-$sisaawal)
                                @elseif ($c==7)
                                  @currency(($awal*$ikey->year41)-$sisaawal)
                                @elseif ($c==8)
                                  @currency(($awal*$ikey->year42)-$sisaawal)
                                @elseif ($c==9)
                                  @currency(($awal*$ikey->year51)-$sisaawal)
                                @elseif ($c==10)
                                  @currency(($awal*$ikey->year52)-$sisaawal)
                              @endif
                            @elseif ($ikey->item=='Dana Pengembangan')
                              @if ($c==4)
                                  @currency(($dsp*$ikey->year22)-$sisadsp)
                                @elseif ($c==2)
                                  @currency(($dsp*$ikey->year12)-$sisadsp)
                                @elseif ($c==3)
                                  @currency(($dsp*$ikey->year21)-$sisadsp)
                                @elseif ($c==1)
                                  @currency(($dsp*$ikey->year11)-$sisadsp)
                                @elseif ($c==5)
                                  @currency(($dsp*$ikey->year31)-$sisadsp)
                                @elseif ($c==6)
                                  @currency(($dsp*$ikey->year32)-$sisadsp)
                                @elseif ($c==7)
                                  @currency(($dsp*$ikey->year41)-$sisadsp)
                                @elseif ($c==8)
                                  @currency(($dsp*$ikey->year42)-$sisadsp)
                                @elseif ($c==9)
                                  @currency(($dsp*$ikey->year51)-$sisadsp)
                                @elseif ($c==10)
                                  @currency(($dsp*$ikey->year52)-$sisadsp)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 1')
                              @if ($c==4)
                                  @currency(($spp1*$ikey->year22)-$sisaspp1)
                                @elseif ($c==2)
                                  @currency(($spp1*$ikey->year12)-$sisaspp1)
                                @elseif ($c==3)
                                  @currency(($spp1*$ikey->year21)-$sisaspp1)
                                @elseif ($c==1)
                                  @currency(($spp1*$ikey->year11)-$sisaspp1)
                                @elseif ($c==5)
                                  @currency(($spp1*$ikey->year31)-$sisaspp1)
                                @elseif ($c==6)
                                  @currency(($spp1*$ikey->year32)-$sisaspp1)
                                @elseif ($c==7)
                                  @currency(($spp1*$ikey->year41)-$sisaspp1)
                                @elseif ($c==8)
                                  @currency(($spp1*$ikey->year42)-$sisaspp1)
                                @elseif ($c==9)
                                  @currency(($spp1*$ikey->year51)-$sisaspp1)
                                @elseif ($c==10)
                                  @currency(($spp1*$ikey->year52)-$sisaspp1)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 2')
                              @if ($c==4)
                                  @currency(($spp2*$ikey->year22)-$sisaspp2)
                                @elseif ($c==2)
                                  @currency(($spp2*$ikey->year12)-$sisaspp2)
                                @elseif ($c==3)
                                  @currency(($spp2*$ikey->year21)-$sisaspp2)
                                @elseif ($c==1)
                                  @currency(($spp2*$ikey->year11)-$sisaspp2)
                                @elseif ($c==5)
                                  @currency(($spp2*$ikey->year31)-$sisaspp2)
                                @elseif ($c==6)
                                  @currency(($spp2*$ikey->year32)-$sisaspp2)
                                @elseif ($c==7)
                                  @currency(($spp2*$ikey->year41)-$sisaspp2)
                                @elseif ($c==8)
                                  @currency(($spp2*$ikey->year42)-$sisaspp2)
                                @elseif ($c==9)
                                  @currency(($spp2*$ikey->year51)-$sisaspp2)
                                @elseif ($c==10)
                                  @currency(($spp2*$ikey->year52)-$sisaspp2)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 3')
                              @if ($c==4)
                                  @currency(($spp3*$ikey->year22)-$sisaspp3)
                                @elseif ($c==2)
                                  @currency(($spp3*$ikey->year12)-$sisaspp3)
                                @elseif ($c==3)
                                  @currency(($spp3*$ikey->year21)-$sisaspp3)
                                @elseif ($c==1)
                                  @currency(($spp3*$ikey->year11)-$sisaspp3)
                                @elseif ($c==5)
                                  @currency(($spp3*$ikey->year31)-$sisaspp3)
                                @elseif ($c==6)
                                  @currency(($spp3*$ikey->year32)-$sisaspp3)
                                @elseif ($c==7)
                                  @currency(($spp3*$ikey->year41)-$sisaspp3)
                                @elseif ($c==8)
                                  @currency(($spp3*$ikey->year42)-$sisaspp3)
                                @elseif ($c==9)
                                  @currency(($spp3*$ikey->year51)-$sisaspp3)
                                @elseif ($c==10)
                                  @currency(($spp3*$ikey->year52)-$sisaspp3)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 4')
                              @if ($c==4)
                                  @currency(($spp4*$ikey->year22)-$sisaspp4)
                                @elseif ($c==2)
                                  @currency(($spp4*$ikey->year12)-$sisaspp4)
                                @elseif ($c==3)
                                  @currency(($spp4*$ikey->year21)-$sisaspp4)
                                @elseif ($c==1)
                                  @currency(($spp4*$ikey->year11)-$sisaspp4)
                                @elseif ($c==5)
                                  @currency(($spp4*$ikey->year31)-$sisaspp4)
                                @elseif ($c==6)
                                  @currency(($spp4*$ikey->year32)-$sisaspp4)
                                @elseif ($c==7)
                                  @currency(($spp4*$ikey->year41)-$sisaspp4)
                                @elseif ($c==8)
                                  @currency(($spp4*$ikey->year42)-$sisaspp4)
                                @elseif ($c==9)
                                  @currency(($spp4*$ikey->year51)-$sisaspp4)
                                @elseif ($c==10)
                                  @currency(($spp4*$ikey->year52)-$sisaspp4)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 5')
                              @if ($c==4)
                                  @currency(($spp5*$ikey->year22)-$sisaspp5)
                                @elseif ($c==2)
                                  @currency(($spp5*$ikey->year12)-$sisaspp5)
                                @elseif ($c==3)
                                  @currency(($spp5*$ikey->year21)-$sisaspp5)
                                @elseif ($c==1)
                                  @currency(($spp5*$ikey->year11)-$sisaspp5)
                                @elseif ($c==5)
                                  @currency(($spp5*$ikey->year31)-$sisaspp5)
                                @elseif ($c==6)
                                  @currency(($spp5*$ikey->year32)-$sisaspp5)
                                @elseif ($c==7)
                                  @currency(($spp5*$ikey->year41)-$sisaspp5)
                                @elseif ($c==8)
                                  @currency(($spp5*$ikey->year42)-$sisaspp5)
                                @elseif ($c==9)
                                  @currency(($spp5*$ikey->year51)-$sisaspp5)
                                @elseif ($c==10)
                                  @currency(($spp5*$ikey->year52)-$sisaspp5)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 6')
                              @if ($c==4)
                                  @currency(($spp6*$ikey->year22)-$sisaspp6)
                                @elseif ($c==2)
                                  @currency(($spp6*$ikey->year12)-$sisaspp6)
                                @elseif ($c==3)
                                  @currency(($spp6*$ikey->year21)-$sisaspp6)
                                @elseif ($c==1)
                                  @currency(($spp6*$ikey->year11)-$sisaspp6)
                                @elseif ($c==5)
                                  @currency(($spp6*$ikey->year31)-$sisaspp6)
                                @elseif ($c==6)
                                  @currency(($spp6*$ikey->year32)-$sisaspp6)
                                @elseif ($c==7)
                                  @currency(($spp6*$ikey->year41)-$sisaspp6)
                                @elseif ($c==8)
                                  @currency(($spp6*$ikey->year42)-$sisaspp6)
                                @elseif ($c==9)
                                  @currency(($spp6*$ikey->year51)-$sisaspp6)
                                @elseif ($c==10)
                                  @currency(($spp6*$ikey->year52)-$sisaspp6)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 7')
                              @if ($c==4)
                                  @currency(($spp7*$ikey->year22)-$sisaspp7)
                                @elseif ($c==2)
                                  @currency(($spp7*$ikey->year12)-$sisaspp7)
                                @elseif ($c==3)
                                  @currency(($spp7*$ikey->year21)-$sisaspp7)
                                @elseif ($c==1)
                                  @currency(($spp7*$ikey->year11)-$sisaspp7)
                                @elseif ($c==5)
                                  @currency(($spp7*$ikey->year31)-$sisaspp7)
                                @elseif ($c==6)
                                  @currency(($spp7*$ikey->year32)-$sisaspp7)
                                @elseif ($c==7)
                                  @currency(($spp7*$ikey->year41)-$sisaspp7)
                                @elseif ($c==8)
                                  @currency(($spp7*$ikey->year42)-$sisaspp7)
                                @elseif ($c==9)
                                  @currency(($spp7*$ikey->year51)-$sisaspp7)
                                @elseif ($c==10)
                                  @currency(($spp7*$ikey->year52)-$sisaspp7)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 8')
                              @if ($c==4)
                                  @currency(($spp8*$ikey->year22)-$sisaspp8)
                                @elseif ($c==2)
                                  @currency(($spp8*$ikey->year12)-$sisaspp8)
                                @elseif ($c==3)
                                  @currency(($spp8*$ikey->year21)-$sisaspp8)
                                @elseif ($c==1)
                                  @currency(($spp8*$ikey->year11)-$sisaspp8)
                                @elseif ($c==5)
                                  @currency(($spp8*$ikey->year31)-$sisaspp8)
                                @elseif ($c==6)
                                  @currency(($spp8*$ikey->year32)-$sisaspp8)
                                @elseif ($c==7)
                                  @currency(($spp8*$ikey->year41)-$sisaspp8)
                                @elseif ($c==8)
                                  @currency(($spp8*$ikey->year42)-$sisaspp8)
                                @elseif ($c==9)
                                  @currency(($spp8*$ikey->year51)-$sisaspp8)
                                @elseif ($c==10)
                                  @currency(($spp8*$ikey->year52)-$sisaspp8)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 9')
                              @if ($c==4)
                                  @currency(($spp9*$ikey->year22)-$sisaspp9)
                                @elseif ($c==2)
                                  @currency(($spp9*$ikey->year12)-$sisaspp9)
                                @elseif ($c==3)
                                  @currency(($spp9*$ikey->year21)-$sisaspp9)
                                @elseif ($c==1)
                                  @currency(($spp9*$ikey->year11)-$sisaspp9)
                                @elseif ($c==5)
                                  @currency(($spp9*$ikey->year31)-$sisaspp9)
                                @elseif ($c==6)
                                  @currency(($spp9*$ikey->year32)-$sisaspp9)
                                @elseif ($c==7)
                                  @currency(($spp9*$ikey->year41)-$sisaspp9)
                                @elseif ($c==8)
                                  @currency(($spp9*$ikey->year42)-$sisaspp9)
                                @elseif ($c==9)
                                  @currency(($spp9*$ikey->year51)-$sisaspp9)
                                @elseif ($c==10)
                                  @currency(($spp9*$ikey->year52)-$sisaspp9)
                              @endif
                            @elseif ($ikey->item=='Biaya SPP 10')
                              @if ($c==4)
                                  @currency(($spp10*$ikey->year22)-$sisaspp10)
                                @elseif ($c==2)
                                  @currency(($spp10*$ikey->year12)-$sisaspp10)
                                @elseif ($c==3)
                                  @currency(($spp10*$ikey->year21)-$sisaspp10)
                                @elseif ($c==1)
                                  @currency(($spp10*$ikey->year11)-$sisaspp10)
                                @elseif ($c==5)
                                  @currency(($spp10*$ikey->year31)-$sisaspp10)
                                @elseif ($c==6)
                                  @currency(($spp10*$ikey->year32)-$sisaspp10)
                                @elseif ($c==7)
                                  @currency(($spp10*$ikey->year41)-$sisaspp10)
                                @elseif ($c==8)
                                  @currency(($spp10*$ikey->year42)-$sisaspp10)
                                @elseif ($c==9)
                                  @currency(($spp10*$ikey->year51)-$sisaspp10)
                                @elseif ($c==10)
                                  @currency(($spp10*$ikey->year52)-$sisaspp10)
                              @endif
                            @elseif ($ikey->item=='Seminar')
                              @if ($c==4)
                                  @currency(($seminar*$ikey->year22)-$sisaseminar)
                                @elseif ($c==2)
                                  @currency(($seminar*$ikey->year12)-$sisaseminar)
                                @elseif ($c==3)
                                  @currency(($seminar*$ikey->year21)-$sisaseminar)
                                @elseif ($c==1)
                                  @currency(($seminar*$ikey->year11)-$sisaseminar)
                                @elseif ($c==5)
                                  @currency(($seminar*$ikey->year31)-$sisaseminar)
                                @elseif ($c==6)
                                  @currency(($seminar*$ikey->year32)-$sisaseminar)
                                @elseif ($c==7)
                                  @currency(($seminar*$ikey->year41)-$sisaseminar)
                                @elseif ($c==8)
                                  @currency(($seminar*$ikey->year42)-$sisaseminar)
                                @elseif ($c==9)
                                  @currency(($seminar*$ikey->year51)-$sisaseminar)
                                @elseif ($c==10)
                                  @currency(($seminar*$ikey->year52)-$sisaseminar)
                              @endif
                            @elseif ($ikey->item=='Sidang')
                              @if ($c==4)
                                  @currency(($sidang*$ikey->year22)-$sisasidang)
                                @elseif ($c==2)
                                  @currency(($sidang*$ikey->year12)-$sisasidang)
                                @elseif ($c==3)
                                  @currency(($sidang*$ikey->year21)-$sisasidang)
                                @elseif ($c==1)
                                  @currency(($sidang*$ikey->year11)-$sisasidang)
                                @elseif ($c==5)
                                  @currency(($sidang*$ikey->year31)-$sisasidang)
                                @elseif ($c==6)
                                  @currency(($sidang*$ikey->year32)-$sisasidang)
                                @elseif ($c==7)
                                  @currency(($sidang*$ikey->year41)-$sisasidang)
                                @elseif ($c==8)
                                  @currency(($sidang*$ikey->year42)-$sisasidang)
                                @elseif ($c==9)
                                  @currency(($sidang*$ikey->year51)-$sisasidang)
                                @elseif ($c==10)
                                  @currency(($sidang*$ikey->year52)-$sisasidang)
                              @endif
                            @elseif ($ikey->item=='Wisuda')
                              @if ($c==4)
                                  @currency(($wisuda*$ikey->year22)-$sisawisuda)
                                @elseif ($c==2)
                                  @currency(($wisuda*$ikey->year12)-$sisawisuda)
                                @elseif ($c==3)
                                  @currency(($wisuda*$ikey->year21)-$sisawisuda)
                                @elseif ($c==1)
                                  @currency(($wisuda*$ikey->year11)-$sisawisuda)
                                @elseif ($c==5)
                                  @currency(($wisuda*$ikey->year31)-$sisawisuda)
                                @elseif ($c==6)
                                  @currency(($wisuda*$ikey->year32)-$sisawisuda)
                                @elseif ($c==7)
                                  @currency(($wisuda*$ikey->year41)-$sisawisuda)
                                @elseif ($c==8)
                                  @currency(($wisuda*$ikey->year42)-$sisawisuda)
                                @elseif ($c==9)
                                  @currency(($wisuda*$ikey->year51)-$sisawisuda)
                                @elseif ($c==10)
                                  @currency(($wisuda*$ikey->year52)-$sisawisuda)
                              @endif
                          @endif
                      </td>
                  </tr>
                  @endforeach

                  <tr>
                    <td><center><b>Total </b></center></td>
                    <td></td>
                    <td align="right"><b>
                    @if ($c==10)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2+$spp3+$spp4+$spp5+$spp6+$spp7+$spp8+$spp9+$spp10+$seminar+$sidang+$wisuda)
                    @elseif ($c==9)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2+$spp3+$spp4+$spp5+$spp6+$spp7+$spp8+$spp9+$seminar+$sidang+$wisuda)
                    @elseif ($c==8)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2+$spp3+$spp4+$spp5+$spp6+$spp7+$spp8+$seminar+$sidang+$wisuda)
                    @elseif ($c==7)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2+$spp3+$spp4+$spp5+$spp6+$spp7+$seminar+$sidang+$wisuda)
                    @elseif ($c==6)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2+$spp3+$spp4+$spp5+$spp6+$seminar+$sidang+$wisuda)
                    @elseif ($c==5)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2+$spp3+$spp4+$spp5+$seminar)
                    @elseif ($c==4)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2+$spp3+$spp4)
                    @elseif ($c==3)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2+$spp3)
                    @elseif ($c==2)
                      @currency($daftar+$awal+$dsp+$spp1+$spp2)
                    @elseif ($c==1)
                        @currency($daftar+$awal+$dsp+$spp1)
                    @endif
                    </b>
                    </td>
                    <td align="right"><b>@currency($totalsisa)</b></td>
                    <td align="right"><b>
                      @if ($c==1)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1))
                        @elseif ($c==2)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2))
                        @elseif ($c==3)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2)+($spp3-$sisaspp3))
                        @elseif ($c==4)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2)+($spp3-$sisaspp3)+($spp4-$sisaspp4))
                        @elseif ($c==5)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2)+($spp3-$sisaspp3)+($spp4-$sisaspp5)+($spp4-$sisaspp5)+($seminar-$sisaseminar))
                        @elseif ($c==6)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2)+($spp3-$sisaspp3)+($spp4-$sisaspp5)+($spp4-$sisaspp5)+($spp6-$sisaspp6)+($seminar-$sisaseminar)+($sidang-$sisasidang)+($wisuda-$sisawisuda))
                        @elseif ($c==7)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2)+($spp3-$sisaspp3)+($spp4-$sisaspp5)+($spp4-$sisaspp5)+($spp6-$sisaspp6)+($spp7-$sisaspp7)+($seminar-$sisaseminar)+($sidang-$sisasidang)+($wisuda-$sisawisuda))
                        @elseif ($c==8)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2)+($spp3-$sisaspp3)+($spp4-$sisaspp5)+($spp4-$sisaspp5)+($spp6-$sisaspp6)+($spp7-$sisaspp7)+($spp8-$sisaspp8)+($seminar-$sisaseminar)+($sidang-$sisasidang)+($wisuda-$sisawisuda))
                        @elseif ($c==9)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2)+($spp3-$sisaspp3)+($spp4-$sisaspp5)+($spp4-$sisaspp5)+($spp6-$sisaspp6)+($spp7-$sisaspp7)+($spp8-$sisaspp8)+($spp9-$sisaspp9)+($seminar-$sisaseminar)+($sidang-$sisasidang)+($wisuda-$sisawisuda))
                        @elseif ($c==10)
                          @currency(($daftar-$sisadaftar)+($awal-$sisaawal)+($dsp-$sisadsp)+($spp1-$sisaspp1)+($spp2-$sisaspp2)+($spp3-$sisaspp3)+($spp4-$sisaspp5)+($spp4-$sisaspp5)+($spp6-$sisaspp6)+($spp7-$sisaspp7)+($spp8-$sisaspp8)+($spp9-$sisaspp9)+($spp10-$sisaspp10)+($seminar-$sisaseminar)+($sidang-$sisasidang)+($wisuda-$sisawisuda))
                      @endif
                      </b>
                    </td>
                  </tr>

                </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection
